services:
  ollama:
    build:
      context: .
    image: ollama_custom
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"  # Port for Ollama service
      - "3050:3050"    # Port for Flask app
    restart: unless-stopped

volumes:
  ollama:
